/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as ClaimRouteImport } from './routes/claim'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClubClubIdRouteImport } from './routes/club.$clubId'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiDevLoginRouteImport } from './routes/api/dev-login'
import { Route as AuthedSuperadminRouteImport } from './routes/_authed/superadmin'
import { Route as AuthedScheduleRouteImport } from './routes/_authed/schedule'
import { Route as AuthedRosterRouteImport } from './routes/_authed/roster'
import { Route as AuthedResourcesRouteImport } from './routes/_authed/resources'
import { Route as AuthedOfficersRouteImport } from './routes/_authed/officers'
import { Route as AuthedNextRouteImport } from './routes/_authed/next'
import { Route as AuthedMeRouteImport } from './routes/_authed/me'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedActivityRouteImport } from './routes/_authed/activity'
import { Route as ClubClubIdIndexRouteImport } from './routes/club.$clubId.index'
import { Route as AuthedSuperadminIndexRouteImport } from './routes/_authed/superadmin/index'
import { Route as ClubClubIdGuestBookRouteImport } from './routes/club.$clubId_.guest-book'
import { Route as ApiPathwaysIngestRouteImport } from './routes/api/pathways/ingest'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthedSuperadminClubIdRouteImport } from './routes/_authed/superadmin/$clubId'
import { Route as AuthedMembersIdRouteImport } from './routes/_authed/members.$id'
import { Route as AuthedMeetingsIdRouteImport } from './routes/_authed/meetings.$id'
import { Route as AuthedAdminVpeDashboardRouteImport } from './routes/_authed/admin/vpe-dashboard'
import { Route as AuthedAdminVpMembershipRouteImport } from './routes/_authed/admin/vp-membership'
import { Route as AuthedAdminSyncTokensRouteImport } from './routes/_authed/admin/sync-tokens'
import { Route as AuthedAdminScheduleRouteImport } from './routes/_authed/admin/schedule'
import { Route as AuthedAdminRolesRouteImport } from './routes/_authed/admin/roles'
import { Route as AuthedAdminPathwaysSyncRouteImport } from './routes/_authed/admin/pathways-sync'
import { Route as AuthedAdminDuesRouteImport } from './routes/_authed/admin/dues'
import { Route as AuthedAdminDcpRouteImport } from './routes/_authed/admin/dcp'
import { Route as AuthedAdminClubSettingsRouteImport } from './routes/_authed/admin/club-settings'
import { Route as ClubClubIdMeetingMeetingIdRouteImport } from './routes/club.$clubId.meeting.$meetingId'
import { Route as AuthedAdminMeetingsNewRouteImport } from './routes/_authed/admin/meetings.new'
import { Route as AuthedAdminMeetingsBatchRouteImport } from './routes/_authed/admin/meetings.batch'
import { Route as ClubClubIdMeetingMeetingIdPrintRouteImport } from './routes/club.$clubId_.meeting.$meetingId.print'
import { Route as ClubClubIdMeetingMeetingIdPresentRouteImport } from './routes/club.$clubId_.meeting.$meetingId.present'
import { Route as ApiMeetingsIdMinutesPdfRouteImport } from './routes/api/meetings.$id.minutes.pdf'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimRoute = ClaimRouteImport.update({
  id: '/claim',
  path: '/claim',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubClubIdRoute = ClubClubIdRouteImport.update({
  id: '/club/$clubId',
  path: '/club/$clubId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDevLoginRoute = ApiDevLoginRouteImport.update({
  id: '/api/dev-login',
  path: '/api/dev-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedSuperadminRoute = AuthedSuperadminRouteImport.update({
  id: '/superadmin',
  path: '/superadmin',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedScheduleRoute = AuthedScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRosterRoute = AuthedRosterRouteImport.update({
  id: '/roster',
  path: '/roster',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedResourcesRoute = AuthedResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOfficersRoute = AuthedOfficersRouteImport.update({
  id: '/officers',
  path: '/officers',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedNextRoute = AuthedNextRouteImport.update({
  id: '/next',
  path: '/next',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMeRoute = AuthedMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedActivityRoute = AuthedActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AuthedRoute,
} as any)
const ClubClubIdIndexRoute = ClubClubIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClubClubIdRoute,
} as any)
const AuthedSuperadminIndexRoute = AuthedSuperadminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedSuperadminRoute,
} as any)
const ClubClubIdGuestBookRoute = ClubClubIdGuestBookRouteImport.update({
  id: '/club/$clubId_/guest-book',
  path: '/club/$clubId/guest-book',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPathwaysIngestRoute = ApiPathwaysIngestRouteImport.update({
  id: '/api/pathways/ingest',
  path: '/api/pathways/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedSuperadminClubIdRoute = AuthedSuperadminClubIdRouteImport.update({
  id: '/$clubId',
  path: '/$clubId',
  getParentRoute: () => AuthedSuperadminRoute,
} as any)
const AuthedMembersIdRoute = AuthedMembersIdRouteImport.update({
  id: '/members/$id',
  path: '/members/$id',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMeetingsIdRoute = AuthedMeetingsIdRouteImport.update({
  id: '/meetings/$id',
  path: '/meetings/$id',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminVpeDashboardRoute = AuthedAdminVpeDashboardRouteImport.update({
  id: '/admin/vpe-dashboard',
  path: '/admin/vpe-dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminVpMembershipRoute = AuthedAdminVpMembershipRouteImport.update({
  id: '/admin/vp-membership',
  path: '/admin/vp-membership',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminSyncTokensRoute = AuthedAdminSyncTokensRouteImport.update({
  id: '/admin/sync-tokens',
  path: '/admin/sync-tokens',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminScheduleRoute = AuthedAdminScheduleRouteImport.update({
  id: '/admin/schedule',
  path: '/admin/schedule',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminRolesRoute = AuthedAdminRolesRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminPathwaysSyncRoute = AuthedAdminPathwaysSyncRouteImport.update({
  id: '/admin/pathways-sync',
  path: '/admin/pathways-sync',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminDuesRoute = AuthedAdminDuesRouteImport.update({
  id: '/admin/dues',
  path: '/admin/dues',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminDcpRoute = AuthedAdminDcpRouteImport.update({
  id: '/admin/dcp',
  path: '/admin/dcp',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminClubSettingsRoute = AuthedAdminClubSettingsRouteImport.update({
  id: '/admin/club-settings',
  path: '/admin/club-settings',
  getParentRoute: () => AuthedRoute,
} as any)
const ClubClubIdMeetingMeetingIdRoute =
  ClubClubIdMeetingMeetingIdRouteImport.update({
    id: '/meeting/$meetingId',
    path: '/meeting/$meetingId',
    getParentRoute: () => ClubClubIdRoute,
  } as any)
const AuthedAdminMeetingsNewRoute = AuthedAdminMeetingsNewRouteImport.update({
  id: '/admin/meetings/new',
  path: '/admin/meetings/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminMeetingsBatchRoute =
  AuthedAdminMeetingsBatchRouteImport.update({
    id: '/admin/meetings/batch',
    path: '/admin/meetings/batch',
    getParentRoute: () => AuthedRoute,
  } as any)
const ClubClubIdMeetingMeetingIdPrintRoute =
  ClubClubIdMeetingMeetingIdPrintRouteImport.update({
    id: '/club/$clubId_/meeting/$meetingId/print',
    path: '/club/$clubId/meeting/$meetingId/print',
    getParentRoute: () => rootRouteImport,
  } as any)
const ClubClubIdMeetingMeetingIdPresentRoute =
  ClubClubIdMeetingMeetingIdPresentRouteImport.update({
    id: '/club/$clubId_/meeting/$meetingId/present',
    path: '/club/$clubId/meeting/$meetingId/present',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMeetingsIdMinutesPdfRoute = ApiMeetingsIdMinutesPdfRouteImport.update({
  id: '/api/meetings/$id/minutes/pdf',
  path: '/api/meetings/$id/minutes/pdf',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/claim': typeof ClaimRoute
  '/signin': typeof SigninRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/activity': typeof AuthedActivityRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/me': typeof AuthedMeRoute
  '/next': typeof AuthedNextRoute
  '/officers': typeof AuthedOfficersRoute
  '/resources': typeof AuthedResourcesRoute
  '/roster': typeof AuthedRosterRoute
  '/schedule': typeof AuthedScheduleRoute
  '/superadmin': typeof AuthedSuperadminRouteWithChildren
  '/api/dev-login': typeof ApiDevLoginRoute
  '/api/health': typeof ApiHealthRoute
  '/club/$clubId': typeof ClubClubIdRouteWithChildren
  '/admin/club-settings': typeof AuthedAdminClubSettingsRoute
  '/admin/dcp': typeof AuthedAdminDcpRoute
  '/admin/dues': typeof AuthedAdminDuesRoute
  '/admin/pathways-sync': typeof AuthedAdminPathwaysSyncRoute
  '/admin/roles': typeof AuthedAdminRolesRoute
  '/admin/schedule': typeof AuthedAdminScheduleRoute
  '/admin/sync-tokens': typeof AuthedAdminSyncTokensRoute
  '/admin/vp-membership': typeof AuthedAdminVpMembershipRoute
  '/admin/vpe-dashboard': typeof AuthedAdminVpeDashboardRoute
  '/meetings/$id': typeof AuthedMeetingsIdRoute
  '/members/$id': typeof AuthedMembersIdRoute
  '/superadmin/$clubId': typeof AuthedSuperadminClubIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/pathways/ingest': typeof ApiPathwaysIngestRoute
  '/club/$clubId/guest-book': typeof ClubClubIdGuestBookRoute
  '/superadmin/': typeof AuthedSuperadminIndexRoute
  '/club/$clubId/': typeof ClubClubIdIndexRoute
  '/admin/meetings/batch': typeof AuthedAdminMeetingsBatchRoute
  '/admin/meetings/new': typeof AuthedAdminMeetingsNewRoute
  '/club/$clubId/meeting/$meetingId': typeof ClubClubIdMeetingMeetingIdRoute
  '/api/meetings/$id/minutes/pdf': typeof ApiMeetingsIdMinutesPdfRoute
  '/club/$clubId/meeting/$meetingId/present': typeof ClubClubIdMeetingMeetingIdPresentRoute
  '/club/$clubId/meeting/$meetingId/print': typeof ClubClubIdMeetingMeetingIdPrintRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/claim': typeof ClaimRoute
  '/signin': typeof SigninRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/activity': typeof AuthedActivityRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/me': typeof AuthedMeRoute
  '/next': typeof AuthedNextRoute
  '/officers': typeof AuthedOfficersRoute
  '/resources': typeof AuthedResourcesRoute
  '/roster': typeof AuthedRosterRoute
  '/schedule': typeof AuthedScheduleRoute
  '/api/dev-login': typeof ApiDevLoginRoute
  '/api/health': typeof ApiHealthRoute
  '/admin/club-settings': typeof AuthedAdminClubSettingsRoute
  '/admin/dcp': typeof AuthedAdminDcpRoute
  '/admin/dues': typeof AuthedAdminDuesRoute
  '/admin/pathways-sync': typeof AuthedAdminPathwaysSyncRoute
  '/admin/roles': typeof AuthedAdminRolesRoute
  '/admin/schedule': typeof AuthedAdminScheduleRoute
  '/admin/sync-tokens': typeof AuthedAdminSyncTokensRoute
  '/admin/vp-membership': typeof AuthedAdminVpMembershipRoute
  '/admin/vpe-dashboard': typeof AuthedAdminVpeDashboardRoute
  '/meetings/$id': typeof AuthedMeetingsIdRoute
  '/members/$id': typeof AuthedMembersIdRoute
  '/superadmin/$clubId': typeof AuthedSuperadminClubIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/pathways/ingest': typeof ApiPathwaysIngestRoute
  '/club/$clubId/guest-book': typeof ClubClubIdGuestBookRoute
  '/superadmin': typeof AuthedSuperadminIndexRoute
  '/club/$clubId': typeof ClubClubIdIndexRoute
  '/admin/meetings/batch': typeof AuthedAdminMeetingsBatchRoute
  '/admin/meetings/new': typeof AuthedAdminMeetingsNewRoute
  '/club/$clubId/meeting/$meetingId': typeof ClubClubIdMeetingMeetingIdRoute
  '/api/meetings/$id/minutes/pdf': typeof ApiMeetingsIdMinutesPdfRoute
  '/club/$clubId/meeting/$meetingId/present': typeof ClubClubIdMeetingMeetingIdPresentRoute
  '/club/$clubId/meeting/$meetingId/print': typeof ClubClubIdMeetingMeetingIdPrintRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/claim': typeof ClaimRoute
  '/signin': typeof SigninRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/_authed/activity': typeof AuthedActivityRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/me': typeof AuthedMeRoute
  '/_authed/next': typeof AuthedNextRoute
  '/_authed/officers': typeof AuthedOfficersRoute
  '/_authed/resources': typeof AuthedResourcesRoute
  '/_authed/roster': typeof AuthedRosterRoute
  '/_authed/schedule': typeof AuthedScheduleRoute
  '/_authed/superadmin': typeof AuthedSuperadminRouteWithChildren
  '/api/dev-login': typeof ApiDevLoginRoute
  '/api/health': typeof ApiHealthRoute
  '/club/$clubId': typeof ClubClubIdRouteWithChildren
  '/_authed/admin/club-settings': typeof AuthedAdminClubSettingsRoute
  '/_authed/admin/dcp': typeof AuthedAdminDcpRoute
  '/_authed/admin/dues': typeof AuthedAdminDuesRoute
  '/_authed/admin/pathways-sync': typeof AuthedAdminPathwaysSyncRoute
  '/_authed/admin/roles': typeof AuthedAdminRolesRoute
  '/_authed/admin/schedule': typeof AuthedAdminScheduleRoute
  '/_authed/admin/sync-tokens': typeof AuthedAdminSyncTokensRoute
  '/_authed/admin/vp-membership': typeof AuthedAdminVpMembershipRoute
  '/_authed/admin/vpe-dashboard': typeof AuthedAdminVpeDashboardRoute
  '/_authed/meetings/$id': typeof AuthedMeetingsIdRoute
  '/_authed/members/$id': typeof AuthedMembersIdRoute
  '/_authed/superadmin/$clubId': typeof AuthedSuperadminClubIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/pathways/ingest': typeof ApiPathwaysIngestRoute
  '/club/$clubId_/guest-book': typeof ClubClubIdGuestBookRoute
  '/_authed/superadmin/': typeof AuthedSuperadminIndexRoute
  '/club/$clubId/': typeof ClubClubIdIndexRoute
  '/_authed/admin/meetings/batch': typeof AuthedAdminMeetingsBatchRoute
  '/_authed/admin/meetings/new': typeof AuthedAdminMeetingsNewRoute
  '/club/$clubId/meeting/$meetingId': typeof ClubClubIdMeetingMeetingIdRoute
  '/api/meetings/$id/minutes/pdf': typeof ApiMeetingsIdMinutesPdfRoute
  '/club/$clubId_/meeting/$meetingId/present': typeof ClubClubIdMeetingMeetingIdPresentRoute
  '/club/$clubId_/meeting/$meetingId/print': typeof ClubClubIdMeetingMeetingIdPrintRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/claim'
    | '/signin'
    | '/unsubscribe'
    | '/activity'
    | '/dashboard'
    | '/me'
    | '/next'
    | '/officers'
    | '/resources'
    | '/roster'
    | '/schedule'
    | '/superadmin'
    | '/api/dev-login'
    | '/api/health'
    | '/club/$clubId'
    | '/admin/club-settings'
    | '/admin/dcp'
    | '/admin/dues'
    | '/admin/pathways-sync'
    | '/admin/roles'
    | '/admin/schedule'
    | '/admin/sync-tokens'
    | '/admin/vp-membership'
    | '/admin/vpe-dashboard'
    | '/meetings/$id'
    | '/members/$id'
    | '/superadmin/$clubId'
    | '/api/auth/$'
    | '/api/pathways/ingest'
    | '/club/$clubId/guest-book'
    | '/superadmin/'
    | '/club/$clubId/'
    | '/admin/meetings/batch'
    | '/admin/meetings/new'
    | '/club/$clubId/meeting/$meetingId'
    | '/api/meetings/$id/minutes/pdf'
    | '/club/$clubId/meeting/$meetingId/present'
    | '/club/$clubId/meeting/$meetingId/print'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/claim'
    | '/signin'
    | '/unsubscribe'
    | '/activity'
    | '/dashboard'
    | '/me'
    | '/next'
    | '/officers'
    | '/resources'
    | '/roster'
    | '/schedule'
    | '/api/dev-login'
    | '/api/health'
    | '/admin/club-settings'
    | '/admin/dcp'
    | '/admin/dues'
    | '/admin/pathways-sync'
    | '/admin/roles'
    | '/admin/schedule'
    | '/admin/sync-tokens'
    | '/admin/vp-membership'
    | '/admin/vpe-dashboard'
    | '/meetings/$id'
    | '/members/$id'
    | '/superadmin/$clubId'
    | '/api/auth/$'
    | '/api/pathways/ingest'
    | '/club/$clubId/guest-book'
    | '/superadmin'
    | '/club/$clubId'
    | '/admin/meetings/batch'
    | '/admin/meetings/new'
    | '/club/$clubId/meeting/$meetingId'
    | '/api/meetings/$id/minutes/pdf'
    | '/club/$clubId/meeting/$meetingId/present'
    | '/club/$clubId/meeting/$meetingId/print'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/claim'
    | '/signin'
    | '/unsubscribe'
    | '/_authed/activity'
    | '/_authed/dashboard'
    | '/_authed/me'
    | '/_authed/next'
    | '/_authed/officers'
    | '/_authed/resources'
    | '/_authed/roster'
    | '/_authed/schedule'
    | '/_authed/superadmin'
    | '/api/dev-login'
    | '/api/health'
    | '/club/$clubId'
    | '/_authed/admin/club-settings'
    | '/_authed/admin/dcp'
    | '/_authed/admin/dues'
    | '/_authed/admin/pathways-sync'
    | '/_authed/admin/roles'
    | '/_authed/admin/schedule'
    | '/_authed/admin/sync-tokens'
    | '/_authed/admin/vp-membership'
    | '/_authed/admin/vpe-dashboard'
    | '/_authed/meetings/$id'
    | '/_authed/members/$id'
    | '/_authed/superadmin/$clubId'
    | '/api/auth/$'
    | '/api/pathways/ingest'
    | '/club/$clubId_/guest-book'
    | '/_authed/superadmin/'
    | '/club/$clubId/'
    | '/_authed/admin/meetings/batch'
    | '/_authed/admin/meetings/new'
    | '/club/$clubId/meeting/$meetingId'
    | '/api/meetings/$id/minutes/pdf'
    | '/club/$clubId_/meeting/$meetingId/present'
    | '/club/$clubId_/meeting/$meetingId/print'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  ClaimRoute: typeof ClaimRoute
  SigninRoute: typeof SigninRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  ApiDevLoginRoute: typeof ApiDevLoginRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ClubClubIdRoute: typeof ClubClubIdRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiPathwaysIngestRoute: typeof ApiPathwaysIngestRoute
  ClubClubIdGuestBookRoute: typeof ClubClubIdGuestBookRoute
  ApiMeetingsIdMinutesPdfRoute: typeof ApiMeetingsIdMinutesPdfRoute
  ClubClubIdMeetingMeetingIdPresentRoute: typeof ClubClubIdMeetingMeetingIdPresentRoute
  ClubClubIdMeetingMeetingIdPrintRoute: typeof ClubClubIdMeetingMeetingIdPrintRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claim': {
      id: '/claim'
      path: '/claim'
      fullPath: '/claim'
      preLoaderRoute: typeof ClaimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/club/$clubId': {
      id: '/club/$clubId'
      path: '/club/$clubId'
      fullPath: '/club/$clubId'
      preLoaderRoute: typeof ClubClubIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dev-login': {
      id: '/api/dev-login'
      path: '/api/dev-login'
      fullPath: '/api/dev-login'
      preLoaderRoute: typeof ApiDevLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/superadmin': {
      id: '/_authed/superadmin'
      path: '/superadmin'
      fullPath: '/superadmin'
      preLoaderRoute: typeof AuthedSuperadminRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/schedule': {
      id: '/_authed/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof AuthedScheduleRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/roster': {
      id: '/_authed/roster'
      path: '/roster'
      fullPath: '/roster'
      preLoaderRoute: typeof AuthedRosterRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/resources': {
      id: '/_authed/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof AuthedResourcesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/officers': {
      id: '/_authed/officers'
      path: '/officers'
      fullPath: '/officers'
      preLoaderRoute: typeof AuthedOfficersRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/next': {
      id: '/_authed/next'
      path: '/next'
      fullPath: '/next'
      preLoaderRoute: typeof AuthedNextRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/me': {
      id: '/_authed/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AuthedMeRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/activity': {
      id: '/_authed/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AuthedActivityRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/club/$clubId/': {
      id: '/club/$clubId/'
      path: '/'
      fullPath: '/club/$clubId/'
      preLoaderRoute: typeof ClubClubIdIndexRouteImport
      parentRoute: typeof ClubClubIdRoute
    }
    '/_authed/superadmin/': {
      id: '/_authed/superadmin/'
      path: '/'
      fullPath: '/superadmin/'
      preLoaderRoute: typeof AuthedSuperadminIndexRouteImport
      parentRoute: typeof AuthedSuperadminRoute
    }
    '/club/$clubId_/guest-book': {
      id: '/club/$clubId_/guest-book'
      path: '/club/$clubId/guest-book'
      fullPath: '/club/$clubId/guest-book'
      preLoaderRoute: typeof ClubClubIdGuestBookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pathways/ingest': {
      id: '/api/pathways/ingest'
      path: '/api/pathways/ingest'
      fullPath: '/api/pathways/ingest'
      preLoaderRoute: typeof ApiPathwaysIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/superadmin/$clubId': {
      id: '/_authed/superadmin/$clubId'
      path: '/$clubId'
      fullPath: '/superadmin/$clubId'
      preLoaderRoute: typeof AuthedSuperadminClubIdRouteImport
      parentRoute: typeof AuthedSuperadminRoute
    }
    '/_authed/members/$id': {
      id: '/_authed/members/$id'
      path: '/members/$id'
      fullPath: '/members/$id'
      preLoaderRoute: typeof AuthedMembersIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/meetings/$id': {
      id: '/_authed/meetings/$id'
      path: '/meetings/$id'
      fullPath: '/meetings/$id'
      preLoaderRoute: typeof AuthedMeetingsIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/vpe-dashboard': {
      id: '/_authed/admin/vpe-dashboard'
      path: '/admin/vpe-dashboard'
      fullPath: '/admin/vpe-dashboard'
      preLoaderRoute: typeof AuthedAdminVpeDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/vp-membership': {
      id: '/_authed/admin/vp-membership'
      path: '/admin/vp-membership'
      fullPath: '/admin/vp-membership'
      preLoaderRoute: typeof AuthedAdminVpMembershipRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/sync-tokens': {
      id: '/_authed/admin/sync-tokens'
      path: '/admin/sync-tokens'
      fullPath: '/admin/sync-tokens'
      preLoaderRoute: typeof AuthedAdminSyncTokensRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/schedule': {
      id: '/_authed/admin/schedule'
      path: '/admin/schedule'
      fullPath: '/admin/schedule'
      preLoaderRoute: typeof AuthedAdminScheduleRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/roles': {
      id: '/_authed/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AuthedAdminRolesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/pathways-sync': {
      id: '/_authed/admin/pathways-sync'
      path: '/admin/pathways-sync'
      fullPath: '/admin/pathways-sync'
      preLoaderRoute: typeof AuthedAdminPathwaysSyncRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/dues': {
      id: '/_authed/admin/dues'
      path: '/admin/dues'
      fullPath: '/admin/dues'
      preLoaderRoute: typeof AuthedAdminDuesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/dcp': {
      id: '/_authed/admin/dcp'
      path: '/admin/dcp'
      fullPath: '/admin/dcp'
      preLoaderRoute: typeof AuthedAdminDcpRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/club-settings': {
      id: '/_authed/admin/club-settings'
      path: '/admin/club-settings'
      fullPath: '/admin/club-settings'
      preLoaderRoute: typeof AuthedAdminClubSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/club/$clubId/meeting/$meetingId': {
      id: '/club/$clubId/meeting/$meetingId'
      path: '/meeting/$meetingId'
      fullPath: '/club/$clubId/meeting/$meetingId'
      preLoaderRoute: typeof ClubClubIdMeetingMeetingIdRouteImport
      parentRoute: typeof ClubClubIdRoute
    }
    '/_authed/admin/meetings/new': {
      id: '/_authed/admin/meetings/new'
      path: '/admin/meetings/new'
      fullPath: '/admin/meetings/new'
      preLoaderRoute: typeof AuthedAdminMeetingsNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/meetings/batch': {
      id: '/_authed/admin/meetings/batch'
      path: '/admin/meetings/batch'
      fullPath: '/admin/meetings/batch'
      preLoaderRoute: typeof AuthedAdminMeetingsBatchRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/club/$clubId_/meeting/$meetingId/print': {
      id: '/club/$clubId_/meeting/$meetingId/print'
      path: '/club/$clubId/meeting/$meetingId/print'
      fullPath: '/club/$clubId/meeting/$meetingId/print'
      preLoaderRoute: typeof ClubClubIdMeetingMeetingIdPrintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/club/$clubId_/meeting/$meetingId/present': {
      id: '/club/$clubId_/meeting/$meetingId/present'
      path: '/club/$clubId/meeting/$meetingId/present'
      fullPath: '/club/$clubId/meeting/$meetingId/present'
      preLoaderRoute: typeof ClubClubIdMeetingMeetingIdPresentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meetings/$id/minutes/pdf': {
      id: '/api/meetings/$id/minutes/pdf'
      path: '/api/meetings/$id/minutes/pdf'
      fullPath: '/api/meetings/$id/minutes/pdf'
      preLoaderRoute: typeof ApiMeetingsIdMinutesPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthedSuperadminRouteChildren {
  AuthedSuperadminClubIdRoute: typeof AuthedSuperadminClubIdRoute
  AuthedSuperadminIndexRoute: typeof AuthedSuperadminIndexRoute
}

const AuthedSuperadminRouteChildren: AuthedSuperadminRouteChildren = {
  AuthedSuperadminClubIdRoute: AuthedSuperadminClubIdRoute,
  AuthedSuperadminIndexRoute: AuthedSuperadminIndexRoute,
}

const AuthedSuperadminRouteWithChildren =
  AuthedSuperadminRoute._addFileChildren(AuthedSuperadminRouteChildren)

interface AuthedRouteChildren {
  AuthedActivityRoute: typeof AuthedActivityRoute
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedMeRoute: typeof AuthedMeRoute
  AuthedNextRoute: typeof AuthedNextRoute
  AuthedOfficersRoute: typeof AuthedOfficersRoute
  AuthedResourcesRoute: typeof AuthedResourcesRoute
  AuthedRosterRoute: typeof AuthedRosterRoute
  AuthedScheduleRoute: typeof AuthedScheduleRoute
  AuthedSuperadminRoute: typeof AuthedSuperadminRouteWithChildren
  AuthedAdminClubSettingsRoute: typeof AuthedAdminClubSettingsRoute
  AuthedAdminDcpRoute: typeof AuthedAdminDcpRoute
  AuthedAdminDuesRoute: typeof AuthedAdminDuesRoute
  AuthedAdminPathwaysSyncRoute: typeof AuthedAdminPathwaysSyncRoute
  AuthedAdminRolesRoute: typeof AuthedAdminRolesRoute
  AuthedAdminScheduleRoute: typeof AuthedAdminScheduleRoute
  AuthedAdminSyncTokensRoute: typeof AuthedAdminSyncTokensRoute
  AuthedAdminVpMembershipRoute: typeof AuthedAdminVpMembershipRoute
  AuthedAdminVpeDashboardRoute: typeof AuthedAdminVpeDashboardRoute
  AuthedMeetingsIdRoute: typeof AuthedMeetingsIdRoute
  AuthedMembersIdRoute: typeof AuthedMembersIdRoute
  AuthedAdminMeetingsBatchRoute: typeof AuthedAdminMeetingsBatchRoute
  AuthedAdminMeetingsNewRoute: typeof AuthedAdminMeetingsNewRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedActivityRoute: AuthedActivityRoute,
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedMeRoute: AuthedMeRoute,
  AuthedNextRoute: AuthedNextRoute,
  AuthedOfficersRoute: AuthedOfficersRoute,
  AuthedResourcesRoute: AuthedResourcesRoute,
  AuthedRosterRoute: AuthedRosterRoute,
  AuthedScheduleRoute: AuthedScheduleRoute,
  AuthedSuperadminRoute: AuthedSuperadminRouteWithChildren,
  AuthedAdminClubSettingsRoute: AuthedAdminClubSettingsRoute,
  AuthedAdminDcpRoute: AuthedAdminDcpRoute,
  AuthedAdminDuesRoute: AuthedAdminDuesRoute,
  AuthedAdminPathwaysSyncRoute: AuthedAdminPathwaysSyncRoute,
  AuthedAdminRolesRoute: AuthedAdminRolesRoute,
  AuthedAdminScheduleRoute: AuthedAdminScheduleRoute,
  AuthedAdminSyncTokensRoute: AuthedAdminSyncTokensRoute,
  AuthedAdminVpMembershipRoute: AuthedAdminVpMembershipRoute,
  AuthedAdminVpeDashboardRoute: AuthedAdminVpeDashboardRoute,
  AuthedMeetingsIdRoute: AuthedMeetingsIdRoute,
  AuthedMembersIdRoute: AuthedMembersIdRoute,
  AuthedAdminMeetingsBatchRoute: AuthedAdminMeetingsBatchRoute,
  AuthedAdminMeetingsNewRoute: AuthedAdminMeetingsNewRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface ClubClubIdRouteChildren {
  ClubClubIdIndexRoute: typeof ClubClubIdIndexRoute
  ClubClubIdMeetingMeetingIdRoute: typeof ClubClubIdMeetingMeetingIdRoute
}

const ClubClubIdRouteChildren: ClubClubIdRouteChildren = {
  ClubClubIdIndexRoute: ClubClubIdIndexRoute,
  ClubClubIdMeetingMeetingIdRoute: ClubClubIdMeetingMeetingIdRoute,
}

const ClubClubIdRouteWithChildren = ClubClubIdRoute._addFileChildren(
  ClubClubIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  ClaimRoute: ClaimRoute,
  SigninRoute: SigninRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  ApiDevLoginRoute: ApiDevLoginRoute,
  ApiHealthRoute: ApiHealthRoute,
  ClubClubIdRoute: ClubClubIdRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiPathwaysIngestRoute: ApiPathwaysIngestRoute,
  ClubClubIdGuestBookRoute: ClubClubIdGuestBookRoute,
  ApiMeetingsIdMinutesPdfRoute: ApiMeetingsIdMinutesPdfRoute,
  ClubClubIdMeetingMeetingIdPresentRoute:
    ClubClubIdMeetingMeetingIdPresentRoute,
  ClubClubIdMeetingMeetingIdPrintRoute: ClubClubIdMeetingMeetingIdPrintRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
